#!/usr/bin/perl
#
# Host Generator
# Feb 1, 2012 by Shou Ya(zxyzxy12321@gmail.com)
#
# For mister Huang's request.
#

use strict;
use Socket;


my @hostlst;

sub scan_config {
    open my $config_file, '<', shift or die "cannot open config file";
    my $version = <$config_file>;
    (($version =~ s/^.*VER\((.*?)\).*$/$1/) > 1.0)
	and die "config file version is too new";
    while (<$config_file>) {
	chomp;
	next if /^\s*$/;
	next if /^\s*#/;
	push @hostlst, $_;
    }
}


sub gen_host {
    my $outstr;

    (!@hostlst) and die "the host list is empty";
    for (@hostlst) {
	my $ip = gethostbyname($_);
	(defined $ip) && do {
	    $outstr .= $_ . "\t\t" . inet_ntoa($ip);
	} || do {
	    $outstr .= "#unkown host: " . $_;
	};
	
	$outstr .= "\n";
    }
    $outstr;
}


sub parse_arg {
    my $config = 0;
    for (@ARGV) {
	$config && do {
	    &scan_config($_);
	    return;
	} ||
	qr/-c|--config/ && do {
	    $config = 1;
	    next;
	} ||
	qr/-h|--help|-\?/ && do {
	    &print_help;
	    return;
	};
    }
    &print_help and exit;
}


sub print_help {
    chop ($0 =`basename $0`);
    print << "eof"

$0 - generate /etc/host file by given host list.

USAGE
  $0 -c config_file

OPTIONS
  -c FILE, --config FILE\tspecial a FILE contains a host list to scan.
  -h, -?, --help\t\tdisplay this help.

ENVIRONMENT
  Please run this script under a proxy that can generate out the correct host
  to through the DNS pollution.

VERSION
  1.0

COPYRIGHT
  Copyright (c) 2012 Shou Ya.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
  This is free software: you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.
eof
}




&parse_arg();

print "The following hosts generated by $0\n";
print "-------------------\n";
print "Please wait...";
$_ = &gen_host();
print "\r";
print;


=POD
That is the end of the script

have a nice dream :)
=cut
